kind: NginxIngress
apiVersion: charts.nginx.org/v1alpha1
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  type: deployment
  image:
    repository: nginx/nginx-ingress
    tag: edge
    pullPolicy: Always
  reportIngressStatus:
      annotations: {}
      enable: true
      enableLeaderElection: true
      ingressLink: true
  serviceType: NodePort