apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-cafe
  namespace: cafeone
  labels:
    f5cr: "true"
spec:
  domainName: cafeone.example.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/ocp.f5demo.com
    monitor:
    - interval: 10
      recv: ""
      send: "GET /tea HTTP/1.1\r\nHost: cafeone.example.com\r\n"
      timeout: 31
      type: https