apiVersion: cis.f5.com/v1
kind: Policy
metadata: 
  labels: 
    f5cr: "true"
  name: type-lb
  namespace: cafeone
spec:
  l7Policies:
    waf: /Common/WAF_Policy
  profiles: 
    logProfiles: 
      - /Common/Common/Log all requests