apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    f5nr: "true"
  name: cafe-mocha-edge
  namespace: cafeone
spec:
  host: cafeone.example.com
  path: "/mocha"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: mocha-svc