apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    f5nr: "true"
  name: cafe-coffee-edge
  namespace: cafeone
spec:
  host: cafeone.example.com
  path: "/coffee"
  port:
    targetPort: 8080
  tls:
    serverSSL: /Common/serverssl
    reference: bigip
  to:
    kind: Service
    name: coffee-svc