---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-deployment
    template: null
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-bigip-ctlr-deployment
    spec:
      containers:
        - args:
            - --bigip-partition
            - test
            - --bigip-url
            - 10.145.74.86
            - --bigip-username
            - admin
            - --bigip-password
            - admin
            - --verify-interval
            - "200"
            - --node-poll-interval
            - "100"
            - --log-level
            - DEBUG
            - --as3-validation=true
            - --disable-teems=true
            - --insecure
            - --log-as3-response
            - --cccl-gtm-agent=False
            - --controller-mode=openshift
            - --route-spec-configmap=kube-system/global-spec-config
            - --route-label=systest
            - --pool-member-type
            - nodeport
          command:
            - /app/bin/k8s-bigip-ctlr
          image: docker.io/nandakishoref5/k8s-bigip-ctlr:mcMay
          imagePullPolicy: IfNotPresent
          name: k8s-bigip-ctlr-deployment
          resources: {}
          terminationMessagePath: /dev/termination-log