apiVersion: v1
kind: ConfigMap
metadata:
  name: global-cm
  namespace: kube-system
  labels:
    f5nr: "true"
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: cafeone
      vserverAddr: 10.192.125.65
      vserverName: cafeone
      allowOverride: true
      tls:
        serverSSL: /Common/serverssl
        reference: bigip
    - namespace: cafetwo
      vserverAddr: 10.192.125.66
      vserverName: cafetwo
      allowOverride: true
      tls:
        serverSSL: /Common/serverssl
        reference: bigip