kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: cafe
  labels:
    f5nr: "true"
  name: cafe-mocha
spec:
  host: cafe.example.com
  path: "/mocha"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: mocha-svc