kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: cafe
  labels:
    f5tnr: "true"
  name: cafe-coffee
spec:
  host: cafe.example.com
  path: "/coffee"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: coffee-svc